import styles from './Main.module.scss'

export const Main = () => {
	return (
	  <main className={styles.wrapper}>
		  <h2>My First React App</h2>
		  <p>occoncini cheese triangles croque monsieur. Cheesy grin caerphilly cream cheese cauliflower cheese dolcelatte cheddar gouda babybel. Roquefort babybel cheddar monterey jack fondue stinking bishop feta bocconcini. Fondue rubber cheese say cheese goat the big cheese feta cheese slices fromage frais. Croque monsieur emmental when the cheese comes out everybody's happy jarlsberg rubber cheese say cheese who moved my cheese swiss. Stinking bishop gouda cheese triangles cheesy feet the big cheese melted cheese squirty cheese danish fontina. Jarlsberg paneer when the cheese comes out everybody's happy feta camembert de normandie the big cheese manchego cheesy grin. Cheddar mozzarella melted cheese cauliflower cheese who moved my cheese pecorino babybel cut the cheese. Pepper jack cheese strings mozzarella halloumi mozzarella cheese and wine monterey jack everyone loves. Bavarian bergkase mozzarella.</p>
			<p>Babybel cheese and biscuits cheese triangles. Camembert de normandie stinking bishop cheesecake cottage cheese goat brie cream cheese cheese slices. Rubber cheese jarlsberg queso cauliflower cheese caerphilly cauliflower cheese cheese and biscuits emmental. Cow pecorino queso cheddar cheese on toast paneer when the cheese comes out everybody's happy hard cheese. Fromage dolcelatte macaroni cheese paneer stinking bishop babybel taleggio paneer. Cow cheesy grin feta cauliflower cheese monterey jack red leicester stilton who moved my cheese. Cheeseburger cauliflower cheese macaroni cheese cheesy feet cauliflower cheese cheese triangles goat bavarian bergkase. Cheesy feet who moved my cheese cheese triangles ricotta cheese on toast when the cheese comes out everybody's happy hard cheese edam. Cauliflower cheese swiss jarlsberg bocconcini hard cheese cheese on toast fromage macaroni cheese. Roquefort fondue paneer jarlsberg danish fontina pecorino squirty cheese pepper jack. Boursin cheese triangles smelly cheese who moved my cheese dolcelatte parmesan brie red leicester. Edam cottage cheese paneer.</p>
	</main>
	)
  }